import { createClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import type { Analysis } from "@/types";
import { InteractiveAttentionChart } from "@/components/analysis/InteractiveAttentionChart";
import { MetricsGrid } from "@/components/analysis/MetricsGrid";
import { DropTimeline } from "@/components/analysis/DropTimeline";
import { TranscriptPanel } from "@/components/analysis/TranscriptPanel";
import { RecommendationList } from "@/components/analysis/RecommendationList";
import { AnalysisActions } from "@/components/analysis/AnalysisActions";
import { InfoTooltip } from "@/components/analysis/InfoTooltip";
import { gradeColor } from "@/lib/utils";
import Link from "next/link";
import { Loader2, AlertCircle } from "lucide-react";

export const metadata: Metadata = { title: "Analysis Results" };

export default async function AnalysisPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { data: job } = await supabase
    .from("jobs").select("*").eq("id", id).eq("user_id", user.id).single();

  if (!job) notFound();

  if (job.status === "pending" || job.status === "processing") {
    return <ProcessingView jobId={id} status={job.status} />;
  }
  if (job.status === "failed") {
    return <FailedView error={job.error_message} />;
  }

  const { data: analysis } = await supabase
    .from("analyses").select("*").eq("job_id", id).eq("user_id", user.id).single();

  if (!analysis) notFound();
  const a = analysis as Analysis;

  return (
    <div className="p-4 sm:p-8 max-w-5xl mx-auto flex flex-col gap-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-start gap-4">
        <div className="min-w-0 flex-1">
          <Link href="/dashboard" className="text-xs font-medium mb-2 inline-flex items-center gap-1" style={{ color: "var(--color-muted)" }}>
            ← Dashboard
          </Link>
          <h1
            className="text-xl sm:text-2xl font-bold break-words"
            title={job.original_name ?? job.youtube_title ?? "Analysis Results"}
            style={{ color: "var(--color-accent)" }}
          >
            {job.original_name ?? job.youtube_title ?? "Analysis Results"}
          </h1>
          <p className="text-sm mt-1 mb-3" style={{ color: "var(--color-muted)" }}>
            Analyzed {new Date(a.created_at).toLocaleString()}
          </p>
          <AnalysisActions jobId={id} />
        </div>

        <div className="flex sm:flex-col items-center sm:items-end gap-3 flex-shrink-0">
          <div className="flex flex-col items-center gap-1 rounded-2xl border p-4" style={{ background: "var(--color-surface)", borderColor: "var(--color-border)" }}>
            <span className={`text-4xl font-bold ${gradeColor(a.grade)}`}>{a.grade}</span>
            <span className="text-2xl font-semibold" style={{ color: "var(--color-accent)" }}>{a.overall_score.toFixed(0)}</span>
            <span className="text-xs" style={{ color: "var(--color-muted)" }}>Overall Score</span>
          </div>
        </div>
      </div>

      {/* Tags */}
      {a.gpt_tags && a.gpt_tags.length > 0 && (
        <div className="flex flex-wrap gap-2">
          {a.gpt_tags.map((tag) => (
            <span key={tag} className="text-xs px-2.5 py-1 rounded-full" style={{ background: "#EFF6FF", color: "var(--color-primary)" }}>
              {tag}
            </span>
          ))}
        </div>
      )}

      {/* Summary */}
      <div className="rounded-xl border p-5" style={{ background: "var(--color-surface)", borderColor: "var(--color-border)" }}>
        <div className="flex items-center gap-2 mb-2">
          <h3 className="text-sm font-semibold" style={{ color: "var(--color-accent)" }}>AI Summary</h3>
          <InfoTooltip text="A high-level overview of your video's content and performance, generated by AI from the transcript and attention data. Use this as a starting point, not a final verdict." />
        </div>
        <p className="text-sm leading-relaxed" style={{ color: "var(--color-text)" }}>{a.gpt_summary}</p>
      </div>

      {/* Hook */}
      {a.gpt_hook_analysis && (
        <div className="rounded-xl border p-5" style={{ background: "#FFFBEB", borderColor: "#FDE68A" }}>
          <div className="flex items-center gap-2 mb-2">
            <h3 className="text-sm font-semibold" style={{ color: "#92400E" }}>Hook Analysis</h3>
            <InfoTooltip text="Analysis of your opening seconds — typically the first 5–15s. This is the highest-leverage part of any video. A weak hook means most viewers leave before the content even starts." />
          </div>
          <p className="text-sm leading-relaxed" style={{ color: "#78350F" }}>{a.gpt_hook_analysis}</p>
        </div>
      )}

      <MetricsGrid analysis={a} />

      {a.attention_curve.length > 0 && (
        <InteractiveAttentionChart
          data={a.attention_curve}
          drops={a.attention_drops}
          recs={a.gpt_recommendations}
        />
      )}

      <DropTimeline drops={a.attention_drops} />

      {a.gpt_recommendations.length > 0 && (
        <RecommendationList recs={a.gpt_recommendations} />
      )}

      {a.transcript_segments.length > 0 && (
        <TranscriptPanel segments={a.transcript_segments} fullText={a.full_transcript} />
      )}

      {/* Feedback callout */}
      <div
        className="rounded-2xl border p-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"
        style={{ background: "linear-gradient(135deg, #EFF6FF 0%, #F5F3FF 100%)", borderColor: "#BFDBFE" }}
      >
        <div>
          <p className="font-semibold text-sm mb-1" style={{ color: "#1E3A8A" }}>
            Was this analysis helpful?
          </p>
          <p className="text-xs leading-relaxed" style={{ color: "#3B82F6" }}>
            Your feedback helps improve Vilyze — one person reads every message.
          </p>
        </div>
        <Link
          href="/support"
          className="self-start sm:self-auto flex-shrink-0 px-4 py-2 rounded-xl text-sm font-semibold text-white whitespace-nowrap"
          style={{ background: "#2563EB" }}
        >
          Rate &amp; Feedback →
        </Link>
      </div>
    </div>
  );
}

function ProcessingView({ status }: { jobId: string; status: string }) {
  return (
    <div className="flex flex-col items-center justify-center min-h-[60vh] gap-4 p-8">
      <Loader2 size={40} className="animate-spin" color="var(--color-primary)" strokeWidth={2} />
      <div className="text-center">
        <p className="font-semibold text-lg" style={{ color: "var(--color-accent)" }}>
          {status === "pending" ? "Queued for analysis…" : "Analyzing your video…"}
        </p>
        <p className="text-sm mt-1" style={{ color: "var(--color-muted)" }}>
          This usually takes 1–2 minutes. You can close this tab and come back.
        </p>
      </div>
      <Link href="/dashboard" className="text-sm font-medium" style={{ color: "var(--color-primary)" }}>
        ← Back to dashboard
      </Link>
    </div>
  );
}

function FailedView({ error }: { error: string | null }) {
  return (
    <div className="flex flex-col items-center justify-center min-h-[60vh] gap-4 p-8">
      <div className="w-14 h-14 rounded-full flex items-center justify-center" style={{ background: "#FEE2E2" }}>
        <AlertCircle size={28} color="var(--color-error)" strokeWidth={2} />
      </div>
      <div className="text-center">
        <p className="font-semibold text-lg" style={{ color: "var(--color-accent)" }}>Analysis failed</p>
        <p className="text-sm mt-1 max-w-sm" style={{ color: "var(--color-muted)" }}>
          {error ?? "An unexpected error occurred. Please try again."}
        </p>
      </div>
      <Link href="/dashboard/upload" className="px-4 py-2 rounded-xl text-sm font-semibold text-white" style={{ background: "var(--color-primary)" }}>
        Try again
      </Link>
    </div>
  );
}
