import type { Recommendation } from "@/types";
import { formatDuration } from "@/lib/utils";
import { InfoTooltip } from "./InfoTooltip";

const PRIORITY_STYLES = {
  high:   { bg: "#FEF2F2", border: "#FECACA", text: "#991B1B", badge: "High" },
  medium: { bg: "#FFFBEB", border: "#FDE68A", text: "#92400E", badge: "Medium" },
  low:    { bg: "#F0FDF4", border: "#BBF7D0", text: "#065F46", badge: "Low" },
};

export function RecommendationList({ recs }: { recs: Recommendation[] }) {
  const sorted = [...recs].sort((a, b) => {
    const order = { high: 0, medium: 1, low: 2 };
    return (order[a.priority] ?? 3) - (order[b.priority] ?? 3);
  });

  return (
    <div className="rounded-xl border p-5" style={{ background: "var(--color-surface)", borderColor: "var(--color-border)" }}>
      <div className="flex items-center gap-2 mb-4">
        <h3 className="text-sm font-semibold" style={{ color: "var(--color-accent)" }}>
          AI Recommendations ({recs.length})
        </h3>
        <InfoTooltip text="Action items generated by AI based on your video's attention data and transcript. Sorted by priority — High items have the most impact on viewer retention." />
      </div>
      <div className="flex flex-col gap-3">
        {sorted.map((r, i) => {
          const s = PRIORITY_STYLES[r.priority] ?? PRIORITY_STYLES.low;
          return (
            <div key={i} className="flex gap-3 p-3 rounded-lg border" style={{ background: s.bg, borderColor: s.border }}>
              <span className="text-xs font-semibold px-2 py-0.5 rounded flex-shrink-0 h-fit" style={{ background: s.border, color: s.text }}>
                {s.badge}
              </span>
              <div>
                <p className="text-sm" style={{ color: "var(--color-text)" }}>{r.text}</p>
                {r.timestamp != null && (
                  <p className="text-xs mt-1" style={{ color: "var(--color-muted)" }}>
                    At {formatDuration(r.timestamp)}
                  </p>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
