"use client";

import { useState } from "react";
import type { TranscriptSegment } from "@/types";
import { formatDuration } from "@/lib/utils";
import { InfoTooltip } from "./InfoTooltip";

export function TranscriptPanel({ segments, fullText }: { segments: TranscriptSegment[]; fullText?: string | null }) {
  const [view, setView] = useState<"segments" | "full">("segments");

  return (
    <div className="rounded-xl border" style={{ background: "var(--color-surface)", borderColor: "var(--color-border)" }}>
      <div className="flex items-center justify-between p-5 border-b" style={{ borderColor: "var(--color-border)" }}>
        <div className="flex items-center gap-2">
          <h3 className="text-sm font-semibold" style={{ color: "var(--color-accent)" }}>Transcript</h3>
          <InfoTooltip text="Speech-to-text generated by Whisper AI. Accuracy depends on audio quality — expect occasional errors, especially with accents, technical terms, or background noise." />
        </div>
        <div className="flex rounded-lg overflow-hidden border text-xs" style={{ borderColor: "var(--color-border)" }}>
          {(["segments", "full"] as const).map((v) => (
            <button
              key={v}
              onClick={() => setView(v)}
              className="px-3 py-1.5 capitalize"
              style={{
                background: view === v ? "var(--color-primary)" : "transparent",
                color: view === v ? "#fff" : "var(--color-muted)",
              }}
            >
              {v}
            </button>
          ))}
        </div>
      </div>

      {/* Accuracy hint */}
      <div className="px-5 pt-3 pb-0">
        <p className="text-[11px] px-3 py-1.5 rounded-lg" style={{ background: "#FFFBEB", color: "#92400E", border: "1px solid #FDE68A" }}>
          ⚠ Transcripts are AI-generated and may contain errors. Verify important quotes manually.
        </p>
      </div>

      <div className="p-5 max-h-72 overflow-y-auto">
        {view === "segments" ? (
          <div className="flex flex-col gap-2">
            {segments.map((s, i) => (
              <div key={i} className="flex gap-3">
                <span className="text-xs font-mono flex-shrink-0 pt-0.5" style={{ color: "var(--color-primary)", minWidth: "3rem" }}>
                  {formatDuration(s.start)}
                </span>
                <p className="text-sm leading-relaxed" style={{ color: "var(--color-text)" }}>{s.text}</p>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-sm leading-relaxed whitespace-pre-wrap" style={{ color: "var(--color-text)" }}>
            {fullText ?? segments.map((s) => s.text).join(" ")}
          </p>
        )}
      </div>
    </div>
  );
}
