import { createClient as createServiceClient } from "@supabase/supabase-js";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import type { Analysis } from "@/types";
import { InteractiveAttentionChart } from "@/components/analysis/InteractiveAttentionChart";
import { MetricsGrid } from "@/components/analysis/MetricsGrid";
import { DropTimeline } from "@/components/analysis/DropTimeline";
import { TranscriptPanel } from "@/components/analysis/TranscriptPanel";
import { RecommendationList } from "@/components/analysis/RecommendationList";
import { InfoTooltip } from "@/components/analysis/InfoTooltip";
import { gradeColor } from "@/lib/utils";
import Link from "next/link";

export const metadata: Metadata = { title: "Shared Analysis" };

export default async function SharePage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;

  const service = createServiceClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );

  const { data: job } = await service
    .from("jobs")
    .select("id, original_name, youtube_title, share_token, status")
    .eq("share_token", token)
    .single();

  if (!job || job.status !== "done") notFound();

  const { data: analysis } = await service
    .from("analyses")
    .select("*")
    .eq("job_id", job.id)
    .single();

  if (!analysis) notFound();
  const a = analysis as Analysis;

  return (
    <div className="min-h-screen" style={{ background: "var(--color-bg)" }}>
      {/* Banner */}
      <div
        className="border-b px-6 py-3 flex items-center justify-between"
        style={{ background: "var(--color-surface)", borderColor: "var(--color-border)" }}
      >
        <Link href="/" className="text-base font-bold" style={{ color: "var(--color-accent)" }}>
          Vilyze
        </Link>
        <div className="flex items-center gap-2">
          <span className="text-xs px-2.5 py-1 rounded-full font-medium" style={{ background: "#EFF6FF", color: "var(--color-primary)" }}>
            Shared Report
          </span>
          <Link
            href="/login"
            className="text-xs font-semibold px-3 py-1.5 rounded-lg text-white"
            style={{ background: "var(--color-primary)" }}
          >
            Analyse your video →
          </Link>
        </div>
      </div>

      <div className="p-4 sm:p-8 max-w-5xl mx-auto flex flex-col gap-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-start gap-4">
          <div className="min-w-0 flex-1">
            <h1
              className="text-xl sm:text-2xl font-bold break-words"
              title={job.original_name ?? job.youtube_title ?? "Analysis Results"}
              style={{ color: "var(--color-accent)" }}
            >
              {job.original_name ?? job.youtube_title ?? "Analysis Results"}
            </h1>
            <p className="text-sm mt-1 mb-3" style={{ color: "var(--color-muted)" }}>
              Analysed {new Date(a.created_at).toLocaleString()}
            </p>
          </div>

          <div className="flex sm:flex-col items-center gap-1 rounded-2xl border p-4 flex-shrink-0 self-start" style={{ background: "var(--color-surface)", borderColor: "var(--color-border)" }}>
            <span className={`text-4xl font-bold ${gradeColor(a.grade)}`}>{a.grade}</span>
            <span className="text-2xl font-semibold" style={{ color: "var(--color-accent)" }}>{a.overall_score.toFixed(0)}</span>
            <span className="text-xs" style={{ color: "var(--color-muted)" }}>Overall Score</span>
          </div>
        </div>

        {/* Tags */}
        {a.gpt_tags && a.gpt_tags.length > 0 && (
          <div className="flex flex-wrap gap-2">
            {a.gpt_tags.map((tag) => (
              <span key={tag} className="text-xs px-2.5 py-1 rounded-full" style={{ background: "#EFF6FF", color: "var(--color-primary)" }}>
                {tag}
              </span>
            ))}
          </div>
        )}

        {/* Summary */}
        <div className="rounded-xl border p-5" style={{ background: "var(--color-surface)", borderColor: "var(--color-border)" }}>
          <div className="flex items-center gap-2 mb-2">
            <h3 className="text-sm font-semibold" style={{ color: "var(--color-accent)" }}>AI Summary</h3>
            <InfoTooltip text="A high-level overview of the video's content and performance, generated by AI from the transcript and attention data." />
          </div>
          <p className="text-sm leading-relaxed" style={{ color: "var(--color-text)" }}>{a.gpt_summary}</p>
        </div>

        {/* Hook */}
        {a.gpt_hook_analysis && (
          <div className="rounded-xl border p-5" style={{ background: "#FFFBEB", borderColor: "#FDE68A" }}>
            <div className="flex items-center gap-2 mb-2">
              <h3 className="text-sm font-semibold" style={{ color: "#92400E" }}>Hook Analysis</h3>
              <InfoTooltip text="Analysis of the opening seconds — this is the highest-leverage part of any video." />
            </div>
            <p className="text-sm leading-relaxed" style={{ color: "#78350F" }}>{a.gpt_hook_analysis}</p>
          </div>
        )}

        <MetricsGrid analysis={a} />

        {a.attention_curve.length > 0 && (
          <InteractiveAttentionChart
            data={a.attention_curve}
            drops={a.attention_drops}
            recs={a.gpt_recommendations}
          />
        )}

        <DropTimeline drops={a.attention_drops} />

        {a.gpt_recommendations.length > 0 && (
          <RecommendationList recs={a.gpt_recommendations} />
        )}

        {a.transcript_segments.length > 0 && (
          <TranscriptPanel segments={a.transcript_segments} fullText={a.full_transcript} />
        )}

        {/* CTA */}
        <div
          className="rounded-2xl border p-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"
          style={{ background: "linear-gradient(135deg, #EFF6FF 0%, #F5F3FF 100%)", borderColor: "#BFDBFE" }}
        >
          <div>
            <p className="font-semibold text-sm mb-1" style={{ color: "#1E3A8A" }}>
              Analyse your own video
            </p>
            <p className="text-xs leading-relaxed" style={{ color: "#3B82F6" }}>
              Get AI-powered insights: attention curves, transcript, engagement metrics, and actionable recommendations.
            </p>
          </div>
          <Link
            href="/login"
            className="self-start sm:self-auto flex-shrink-0 px-4 py-2 rounded-xl text-sm font-semibold text-white whitespace-nowrap"
            style={{ background: "#2563EB" }}
          >
            Try Vilyze free →
          </Link>
        </div>
      </div>
    </div>
  );
}
